# Default values for Gotify.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gotify/server-arm7
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0.22"

secret:
  user: "admin"
  pass: "admin"

env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  GOTIFY_SERVER_PORT: "80"
  GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: "0"
  GOTIFY_SERVER_LISTENADDR: ""
  GOTIFY_SERVER_SSL_ENABLED: "false"
  GOTIFY_SERVER_SSL_REDIRECTTOHTTPS: "true"
  GOTIFY_SERVER_SSL_LISTENADDR: ""
  GOTIFY_SERVER_SSL_PORT: "443"
  GOTIFY_SERVER_SSL_CERTFILE: ""
  GOTIFY_SERVER_SSL_CERTKEY: ""
  GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED: "false"
  GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS: "false"
  GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE: "certs"
  # lists are a little weird but do-able (:
  # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: "- mydomain.tld\n- myotherdomain.tld"
  GOTIFY_SERVER_RESPONSEHEADERS: "X-Custom-Header: \"custom value\""
  # GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  # GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\""
  # GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
  # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: "45"
  GOTIFY_DATABASE_DIALECT: "sqlite3"
  GOTIFY_DATABASE_CONNECTION: "data/gotify.db"
  GOTIFY_PASSSTRENGTH: "10"
  GOTIFY_UPLOADEDIMAGESDIR: "data/images"
  GOTIFY_PLUGINSDIR: "data/plugins"

service:
  port:
    port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  hosts:
    - host: "gotify.192.168.1.189.nip.io"
      paths:
        - path: "/"
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  data:
    enabled: false
    emptyDir: false
    mountPath: /app/data
    ## gotify downloads data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    ##
    ## If you want to reuse an existing claim, you can pass the name of the PVC using
    ## the existingClaim variable
    # existingClaim: your-claim
    accessMode: ReadWriteOnce
    size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    skipuninstall: false
