---
apiVersion: v2
appVersion: "ee287b9"
version: 1.0.0
name: notes
description: A self-hosted note taking web app that lets you keep track of your notes and search them in a easy and minimal way.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/notes"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - markdown
  - notes
  - app
  - web
  - webapp
sources:
  - https://github.com/prologic/notes
  - https://github.com/nicholaswilde/docker-notes
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Change tag to version-ee287b9 in order to reduce the number of chart updates.
    - kind: changed
      description: simply values.yaml
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: notes
      image: ghcr.io/nicholaswilde/notes:version-ee287b9
