---
apiVersion: v2
appVersion: "14.0"
version: 1.0.0
name: odoo
description: All-in-one business software. Beautiful. Easy-to-use. CRM, Accounting, PM, HR, Procurement, Point of Sale, MRP, Marketing, etc.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/odoo"
icon: "https://pbs.twimg.com/profile_images/970608340014419969/1bpCWJhS_400x400.jpg"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: postgres
    version: ~0.1.0
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: postgres.enabled
keywords:
  - odoo
  - crm
  - pm
  - hr
  - accounting
  - mrp
  - marketing
sources:
  - https://www.odoo.com/
  - https://hub.docker.com/repository/docker/nicholaswilde/odoo
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change tag to version-14.0 in order to reduce the number of chart updates
    - kind: changed
      description: Simplify values.yaml
    - kind: changed
      description: Bump common to 0.1.13
  artifacthub.io/images: |
    - name: odoo
      image: ghcr.io/nicholaswilde/odoo:version-14.0
