---
apiVersion: v2
appVersion: "1.5.0"
version: 2.0.0
name: beets
description: A music library manager and not, for the most part, a music player.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/beets"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/beets.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - music
  - library
  - manager
  - player
  - beets
sources:
  - https://github.com/linuxserver/docker-beets
  - https://beets.io/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to version-1.5.0
    - kind: changed
      description: BREAKING! Move to release version 1.5.0
  artifacthub.io/images: |
    - name: beets
      image: ghcr.io/linuxserver/beets:version-1.5.0
