---
apiVersion: v2
appVersion: "ee8a20c"
version: 1.0.0
name: static
description: A self-hosted static file serving app which does nothing more than just serve up static files from a mounted volume.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/static"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - app
  - web
  - filesystem
  - static
sources:
  - https://github.com/prologic/static
  - https://github.com/nicholaswilde/docker-static
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.yaml
    - kind: changed
      description: Change tag to version-ee8a20c in order to reduce the number of chart updates.
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: static
      image: ghcr.io/nicholaswilde/static:version-ee8a20c
