---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/babybuddy
  pullPolicy: IfNotPresent
  tag: "version-v1.9.0"

# See more environment variables in the babybuddy documentation
# https://github.com/linuxserver/docker-babybuddy#parameters
env: {}
  # TZ:

service:
  port:
    port: 8000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config

# Enable postgres
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/postgres/values.yaml
postgres:
  enabled: false
  secret:
    POSTGRES_PASSWORD: "babybuddy-pass"
  env:
    POSTGRES_USER: "babybuddy"
    POSTGRES_DB: "babybuddy-postgres"
  fullnameOverride: babybuddy-postgres
