---
apiVersion: v2
appVersion: "2.2.1"
version: 1.0.0
name: davos
description: An FTP automation tool that periodically scans given host locations for new files.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/davos"
icon: "https://github.com/linuxserver/davos/raw/master/src/main/resources/static/android-chrome-192x192.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
keywords:
  - davos
  - ftp
  - automation
sources:
  - https://github.com/linuxserver/docker-davos
  - https://github.com/linuxserver/davos/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump tag to 2.2.1-ls76
    - kind: changed
      description: Bump common to 0.1.13
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: davos
      image: ghcr.io/linuxserver/davos:2.2.1-ls76
