---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: friendica
  pullPolicy: IfNotPresent
  tag: "2021.04"

secret: {}

# See more environment variables in the friendica documentation
# https://hub.docker.com/_/friendica
env: {}

service:
  port:
    port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /var/www/html

# Enable mariadb
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
mariadb:
  enabled: false
  secret:
    MYSQL_ROOT_PASSWORD: "friendica-pass"
    MYSQL_PASSWORD: "friendica-pass"
  env:
    MYSQL_USER: "friendica"
    MYSQL_DATABASE: "friendica-mariadb"
  fullnameOverride: friendica-mariadb
