---
name: Labels

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yaml'
      - '.github/workflows/labels.yaml'

jobs:
  labeler:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.0.2
      -
        name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.1
